name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3.'
inputs: # example with AWS Bucket S3
  bucket: # Input is the bucket name
    description: 'The S3 bucket name.'
    required: true # Input as bucket name could be everything after all, therefore it is required
  bucket-region: # In AWS you have to select a region where you bucket will be hosted
    description: 'The region of the S3 bucket.'
    required: false
    default: 'us-east-1' # Default value is a guess here; us-east-1 is the default region when you have not picked one in AWS (it is a assumption)
  dist-folder:
    description: 'The folder containing the deployment files.'
    required: true
outputs: # Provide the AWS hosted website url as output to GitHub action so that user can lick on it when action finishes.
  website-url: 
    description: 'The URL of the deployed website.'
runs:
  using: 'docker' # Tells GitHub Action that this is a docker action
  image: 'Dockerfile' # Path to docker file which provides the container; doc: https://docs.github.com/de/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-container-actions
  
